/* Generated By:JavaCC: Do not edit this line. EXceLlenSeConstants.java */
package de.hft_stuttgart.cpl;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EXceLlenSeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 4;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int STRING = 6;
  /** RegularExpression Id. */
  int EQUALS = 7;
  /** RegularExpression Id. */
  int NOT_EQUALS = 8;
  /** RegularExpression Id. */
  int ADD = 9;
  /** RegularExpression Id. */
  int SUB = 10;
  /** RegularExpression Id. */
  int SIGNED = 11;
  /** RegularExpression Id. */
  int EOL = 12;
  /** RegularExpression Id. */
  int MUL = 13;
  /** RegularExpression Id. */
  int DIV = 14;
  /** RegularExpression Id. */
  int MOD = 15;
  /** RegularExpression Id. */
  int AND = 16;
  /** RegularExpression Id. */
  int TIMESTAMP = 17;
  /** RegularExpression Id. */
  int VAR = 18;
  /** RegularExpression Id. */
  int LPAR = 19;
  /** RegularExpression Id. */
  int RPAR = 20;
  /** RegularExpression Id. */
  int LB = 21;
  /** RegularExpression Id. */
  int RB = 22;
  /** RegularExpression Id. */
  int SINGLE_QUOTE = 23;
  /** RegularExpression Id. */
  int FOR = 24;
  /** RegularExpression Id. */
  int FROM = 25;
  /** RegularExpression Id. */
  int TO = 26;
  /** RegularExpression Id. */
  int DO = 27;
  /** RegularExpression Id. */
  int COLUMN = 28;
  /** RegularExpression Id. */
  int ROW = 29;
  /** RegularExpression Id. */
  int FOREND = 30;
  /** RegularExpression Id. */
  int FORMATTED = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<NUMBER>",
    "<DIGIT>",
    "<STRING>",
    "\"=\"",
    "\"<>\"",
    "\"+\"",
    "\"-\"",
    "<SIGNED>",
    "\"\\n\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"&\"",
    "<TIMESTAMP>",
    "<VAR>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"\\\'\"",
    "\"for\"",
    "\"from\"",
    "\"to\"",
    "\"do\"",
    "\"C\"",
    "\"R\"",
    "\"end\"",
    "\"FORMATTED\"",
  };

}
