/* Generated By:JavaCC: Do not edit this line. InterpreterConstants.java */
package de.hft_stuttgart.cpl;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface InterpreterConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGIT = 4;
  /** RegularExpression Id. */
  int DECIMAL = 5;
  /** RegularExpression Id. */
  int FLOAT = 6;
  /** RegularExpression Id. */
  int STRING = 7;
  /** RegularExpression Id. */
  int ADD = 8;
  /** RegularExpression Id. */
  int SUB = 9;
  /** RegularExpression Id. */
  int SIGNED = 10;
  /** RegularExpression Id. */
  int EOL = 11;
  /** RegularExpression Id. */
  int MUL = 12;
  /** RegularExpression Id. */
  int DIV = 13;
  /** RegularExpression Id. */
  int MOD = 14;
  /** RegularExpression Id. */
  int AND = 15;
  /** RegularExpression Id. */
  int SINGLE_QUOTE = 16;
  /** RegularExpression Id. */
  int TIMESTAMP = 17;
  /** RegularExpression Id. */
  int VAR = 18;
  /** RegularExpression Id. */
  int FOR = 19;
  /** RegularExpression Id. */
  int FROM = 20;
  /** RegularExpression Id. */
  int TO = 21;
  /** RegularExpression Id. */
  int DO = 22;
  /** RegularExpression Id. */
  int COLUMN = 23;
  /** RegularExpression Id. */
  int ROW = 24;
  /** RegularExpression Id. */
  int FOREND = 25;
  /** RegularExpression Id. */
  int FORMATTED = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<DIGIT>",
    "<DECIMAL>",
    "<FLOAT>",
    "<STRING>",
    "\"+\"",
    "\"-\"",
    "<SIGNED>",
    "\"\\n\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"&\"",
    "\"\\\'\"",
    "<TIMESTAMP>",
    "<VAR>",
    "\"for\"",
    "\"from\"",
    "\"to\"",
    "\"do\"",
    "\"C\"",
    "\"R\"",
    "\"end\"",
    "\"FORMATTED\"",
    "\"=\"",
  };

}
